In [4]:
# *******************************Python For Data Analysis using NumPy ****************************************
import numpy as np

In [2]:
# Part - 1 NumPy arrays, builtin method, array methods and attrbutes
my_list = [-1,0,1]

In [3]:
my_list, type(my_list)

([-1, 0, 1], list)

In [5]:
my_arr = np.array(my_list)

In [6]:
my_arr, type(my_arr)

(array([-1,  0,  1]), numpy.ndarray)

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]  # list to create numpy array

In [8]:
my_matrix, type(my_matrix)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], list)

In [9]:
matrix_one = np.array(my_matrix)

In [11]:
matrix_one, type(matrix_one)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), numpy.ndarray)

In [12]:
my_tuple = (-1,0,1)

In [13]:
my_arr_t = np.array(my_tuple)

In [14]:
my_arr_t, type(my_arr_t)

(array([-1,  0,  1]), numpy.ndarray)

In [15]:
np.arange(0,11,2) #Start, stop, step

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.arange(0,11,2, dtype = float) # with dataype

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [17]:
np.linspace(1, 15, 15 )

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [18]:
np.linspace(1, 15, 15, retstep = True )

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.]), 1.0)

In [22]:
np.linspace(1, 15, 30, retstep = True ) #Start, stop, number of points

(array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
         3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
         5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
         8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
        10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
        13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ]),
 0.4827586206896552)

In [29]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [30]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.random

<module 'numpy.random' from 'C:\\Users\\Krishna\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [32]:
np.random.rand(3)

array([0.43635323, 0.66402771, 0.00791485])

In [33]:
np.random.rand(3,2) #matrix 3 rows, 2 colums

array([[0.55497224, 0.96329257],
       [0.49859178, 0.02509624],
       [0.0464744 , 0.77163721]])

In [34]:
np.random.randn(4,4) 

array([[-1.02484935,  0.51739597,  0.70773473,  0.10714003],
       [-0.16351891,  1.3617174 ,  0.9279632 , -0.24042555],
       [-0.26849607, -0.18641121,  0.69641108, -1.17216677],
       [ 0.02229299,  1.11936626, -1.97866006, -0.46066229]])

In [36]:
np.random.randint(1,100) # ( low, high )  -----gets single random num between given

39

In [37]:
np.random.randint(1,100, 4) # sie is 4  , gets list of 4 random nums

array([ 6, 22, 24,  4])

In [39]:
np.random.randint(1,100, (4,4))

array([[44, 99, 68, 77],
       [31, 80, 42, 31],
       [96, 57, 24, 78],
       [85, 45, 18, 43]])

In [40]:
arr_arange = np.arange(16)

In [41]:
arr_ranint = np.random.randint(0,100,10)

In [42]:
arr_arange, arr_ranint

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([96,  9, 51,  5, 84,  9, 65, 23,  5, 54]))

In [43]:
arr_arange.reshape(4,4) # it reshapes the 1D array to 2D array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
arr_ranint.max()

96

In [45]:
arr_ranint.min()

5

In [46]:
argmax() and argmin() # used to find index loc of max and min values

NameError: name 'argmax' is not defined

In [47]:
arr_ranint.argmax()

0

In [48]:
arr_ranint.argmin()

3

In [50]:
arr_arange.shape

(16,)

In [51]:
arr_arange.size

16

In [52]:
arr_arange.dtype

dtype('int32')

In [53]:
arr_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
arr_arange.reshape(4,4).shape

(4, 4)

In [57]:
# Part 2 - Indexing, Slicing, broadcasting and boolean masking
arr_1d =  np.array(([11,23,0, -4, 222, 3, 422]))

In [58]:
arr_1d

array([ 11,  23,   0,  -4, 222,   3, 422])

In [59]:
arr_1d[0]

11

In [61]:
arr_1d[0:4], arr_1d # Slicing

(array([11, 23,  0, -4]), array([ 11,  23,   0,  -4, 222,   3, 422]))

In [62]:
arr_1d[-2], arr_1d

(3, array([ 11,  23,   0,  -4, 222,   3, 422]))

In [63]:
arr_1d[:2], arr_1d

(array([11, 23]), array([ 11,  23,   0,  -4, 222,   3, 422]))

In [64]:
arr_1d[2:], arr_1d # anything after 2

(array([  0,  -4, 222,   3, 422]), array([ 11,  23,   0,  -4, 222,   3, 422]))

In [65]:
arr_1d[100], arr_1d

IndexError: index 100 is out of bounds for axis 0 with size 7

In [69]:
arr_2d =  np.arange(24).reshape(6,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
arr_2d[2,2], arr_2d[2][2]

(10, 10)

In [73]:
row = 2
col = 3
arr_2d[row,col]

11

In [74]:
arr_2d[2:4, 2:4]

array([[10, 11],
       [14, 15]])

In [75]:
#broadcasting
arr_1d = np.arange(0,10)
arr_1d


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr_1d[0:5] = 500
arr_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [78]:
arr_2d = np.ones((4,4))
arr_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
arr_2d[0] = 300
arr_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [82]:
arr = np.arange(0,4)
arr

array([0, 1, 2, 3])

In [83]:
arr_2d + arr

array([[300., 301., 302., 303.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [84]:
arr_2d + 300

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [85]:
arr

array([0, 1, 2, 3])

In [88]:
arr2 = np.arange(0,4)[:,np.newaxis]
arr2

array([[0],
       [1],
       [2],
       [3]])

In [89]:
arr_2d = np.zeros((5,5))
arr_2d.shape[1]
for i in range(arr_2d.shape[1]):
    arr_2d[i] = i
arr_2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [90]:
arr_2d[[1,2,3]]

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [91]:
arr_2d[[3,1,4]]

array([[3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4.]])

In [92]:
arr_2d = np.arange(24)
arr_2d.shape = (6,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [93]:
arr_2d[[2,4]] # fetch rows

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [94]:
arr_2d[[5,0]]

array([[20, 21, 22, 23],
       [ 0,  1,  2,  3]])

In [95]:
arr_2d[:,[2,3]] # fetch random rows

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [96]:
#Boolean masking
arr_1 = np.arange(1,11)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
bool_mask = arr_1 > 3
bool_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [99]:
mod_2_mask_1d = 0 == arr_1%2
mod_2_mask_1d

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [100]:
even_val = arr_1[mod_2_mask_1d]
even_val # output to get only even numbers

array([ 2,  4,  6,  8, 10])

In [101]:
arr_2d = np.arange(24)
arr_2d.shape = (6,4)
mod_2_mask_1d = 0 == arr_2d%2 
mod_2_mask_1d

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [107]:
# Part - 3 NumPy - Arthmetic Operations and Universal Functions
arr = np.arange(0,5)
arr , arr+arr ,arr-arr, arr / arr, arr * arr #Arthmetic

C:\Users\Krishna\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


(array([0, 1, 2, 3, 4]),
 array([0, 2, 4, 6, 8]),
 array([0, 0, 0, 0, 0]),
 array([nan,  1.,  1.,  1.,  1.]),
 array([ 0,  1,  4,  9, 16]))

In [108]:
2 * arr

array([0, 2, 4, 6, 8])

In [109]:
#Universal Func
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [110]:
np.max(arr), np.min(arr)

(4, 0)

In [111]:
np.sin(arr) # Trignometric

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [113]:
np.exp(arr) #Exponential

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [114]:
np.log(arr)

C:\Users\Krishna\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [115]:
np.deg2rad(arr) #degree to radient

array([0.        , 0.01745329, 0.03490659, 0.05235988, 0.06981317])

In [116]:
np.rad2deg(np.deg2rad(arr)) #Radient to degreee

array([0., 1., 2., 3., 4.])

In [117]:
#Excercises 

list_1 =  [1,2,3,4,5]
arr = np.array(list_1)
arr

array([1, 2, 3, 4, 5])

In [119]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

In [120]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [122]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [125]:
#Generate array of 5 tens
np.ones(5) * 10

array([10., 10., 10., 10., 10.])

In [126]:
# use arange and generate array if even nms btw 50 -100
np.arange(52, 100, 2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

In [129]:
# generate 1 linearly spaced points btw 0 to 1
np.linspace(0,1,10, retstep=True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

In [130]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [134]:
#convert arr into 2d matrix
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [135]:
arr.shape = (5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [139]:
np.arange(1,26).reshape(5,5) / 10

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

In [142]:
print(np.linspace(0,24,25).reshape(5,5))
print('Step siz is:', np.linspace(0,24,25)[1])

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
Step siz is: 1.0


In [143]:
np.random.rand(1)

array([0.52622644])

In [146]:
# 7X5 matrix with 35 random nums
print(np.random.rand(35).reshape(7,5))

[[0.41821083 0.88768343 0.4940762  0.19932396 0.51502454]
 [0.25784759 0.76826856 0.66471849 0.65499086 0.89125441]
 [0.36878615 0.11941708 0.42679407 0.38127093 0.34970475]
 [0.3757657  0.84191812 0.22225857 0.30401183 0.82543531]
 [0.36810452 0.09329407 0.09946943 0.24530418 0.1965212 ]
 [0.17613573 0.48256381 0.53280242 0.6843693  0.99019333]
 [0.26479524 0.50080159 0.72850189 0.92419811 0.23807894]]


In [147]:
print(np.random.rand(7,5))

[[0.43507016 0.23843169 0.38953586 0.58118679 0.10175823]
 [0.29264567 0.47852388 0.41530104 0.57964205 0.6792613 ]
 [0.63637177 0.50440202 0.36127401 0.08936872 0.02773071]
 [0.72376211 0.98826377 0.41150003 0.91964053 0.28765987]
 [0.18008313 0.33234433 0.86871999 0.80626985 0.43067984]
 [0.44202794 0.58531012 0.25450787 0.83760513 0.92762579]
 [0.76485248 0.93451347 0.62820956 0.45401191 0.04255393]]


In [148]:
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])